resources:
- repo: self

queue:
  demands: msbuild

trigger:
- master
- core3-preview5

variables:
  BuildConfiguration: 'Debug'
  PushNupkg: 'True'
  TeamName: 'Package Experience'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

steps:
- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 3.0.100-preview5-011568
  inputs:
    version: 3.0.100-preview5-011568

- task: DotNetCoreCLI@2
  inputs:
    projects: 'CredentialProvider.Microsoft/CredentialProvider.Microsoft.csproj'
    feedsToUse: config
    nugetConfigPath: 'CredentialProvider.Microsoft/NuGet.config'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'CredentialProvider.Microsoft/CredentialProvider.Microsoft.csproj'
    arguments: '--no-restore'
    feedsToUse: 'select'
    versioningScheme: 'off'